[package]
# Semantic Versionning is used: https://semver.org/
version = "0.0.3"

preview_image = "preview.jpg"

# The title and description fields are primarily for displaying extension info in UI
title = "DHART for Omniverse"
description="An omniverse extension for DHART using the python API."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

icon = "icon.jpg"

# URL of the extension source repository.
repository = "github.com/cadop/ov_dhart"

# One of categories for UI.
category = "Analysis"

# Keywords for the extension
keywords = ["kit", "design","robotics"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.physx" = {}

# Main python module this extension provides, it will be publicly available as "import SiBoRG.analysis.dhart".
[[python.module]]
name = "SiBoRG.analysis.dhart"


[python.pipapi]
use_online_index = true

# Use this to specify a list of additional repositories if your pip package is hosted somewhere other
# than the default repo(s) configured in pip. Will pass these to pip with "--extra-index-url" argument
# repositories = ["https://test.pypi.org/simple/"]

requirements = ["dhart"]